sch-core: CD_Simplex.hxx File Reference
CD_Simplex.hxx File Reference
Functions
template<typename T >
void CD_SimplexExchangeTest (T &a, T &b, T &c)
template<typename T >
void CD_SimplexExchange (T &a, T &b, T &c)
Function Documentation
template<typename T > void CD_SimplexExchange (T & a, T & b, T & c) inline
References sch::CD_Simplex::AB(), sch::CD_Simplex::ab_, sch::CD_Simplex::AC(), sch::CD_Simplex::ac_, sch::CD_Simplex::AD(), sch::CD_Simplex::ad_, sch::CD_None, sch::CD_Point, sch::CD_Segment, sch::CD_Simplex::CD_Simplex(), sch::CD_Tetrahedron, sch::CD_Triangle, sch::CD_Simplex::filter(), sch::CD_Simplex::getType(), CD_Matrix::Vector3T< T, normOptimization >::normsquared(), sch::CD_Simplex::operator!=(), sch::CD_Simplex::operator+(), sch::CD_Simplex::operator+=(), sch::CD_Simplex::operator=(), sch::CD_Simplex::operator==(), sch::CD_Simplex::operator[](), sch::CD_Simplex::s1_, sch::CD_Simplex::s2_, sch::CD_Simplex::s3_, sch::CD_Simplex::s4_, sch::CD_Simplex::squareDistanceAtOrigin(), sch::CD_Simplex::type_, and sch::CD_Simplex::updateVectors().
template<typename T > void CD_SimplexExchangeTest (T & a, T & b, T & c) inline