sch-core: CD_Matrix::Matrix4x4T< T > Struct Template Reference
CD_Matrix::Matrix4x4T< T > Struct Template Reference
#include <sch/Matrix/SmallVector4T.h>
Public Member Functions
Matrix4x4T ()
Matrix4x4T (const T x)
Matrix4x4T (const struct Matrix4x4T< T > &v)
template<typename T2 >
Matrix4x4T (const struct Matrix4x4T< T2 > &v)
T & operator[] (unsigned int i)
const T & operator[] (unsigned int i) const
T & operator() (unsigned int i, unsigned int j)
T operator() (unsigned int i, unsigned int j) const
void setZero (void)
void setIdentity (void)
Matrix4x4T< T > operator+ (const Matrix4x4T< T > &B)
struct Matrix4x4T< T > operator- (const struct Matrix4x4T< T > &B)
Matrix4x4T< T > operator* (const Matrix4x4T< T > &B) const
void CeqthismulB (const Matrix4x4T< T > &B, Matrix4x4T< T > &C) const
void CeqthismulB (const Vector4T< T > &B, Vector4T< T > &C) const
template<bool b>
Vector3T< T, b > operator* (const Vector3T< T, b > &B) const
Matrix4x4T< T > operator* (const double &r)
Matrix4x4T< T > Transpose ()
void Inversion (Matrix4x4T &A)
Matrix4x4T< T > Inversion ()
T determinant () const
T trace () const
void operator+= (const Matrix3x3T< T > &B)
void operator-= (const Matrix4x4T< T > &B)
void operator*= (const Matrix4x4T< T > &B)
Local matrix multiplication.
Public Attributes
T m [16]
Friends
std::ostream & operator<< (std::ostream &os, Matrix4x4T< T > const &A)
Detailed Description
template<typename T>
struct CD_Matrix::Matrix4x4T< T >
Template to handle a 4x4 matrix
Constructor & Destructor Documentation
template<typename T> CD_Matrix::Matrix4x4T< T >::Matrix4x4T () inline
Defaut constructor.
template<typename T> CD_Matrix::Matrix4x4T< T >::Matrix4x4T (const T x) inline
Constructor form a scalar
template<typename T> CD_Matrix::Matrix4x4T< T >::Matrix4x4T (const struct Matrix4x4T< T > & v) inline
Copy constructor
References CD_Matrix::Matrix4x4T< T >::m.
template<typename T> template<typename T2 > CD_Matrix::Matrix4x4T< T >::Matrix4x4T (const struct Matrix4x4T< T2 > & v) inline
Hybrid copy constructor
References CD_Matrix::Matrix4x4T< T >::m.
Member Function Documentation
template<typename T> void CD_Matrix::Matrix4x4T< T >::CeqthismulB (const Matrix4x4T< T > & B, Matrix4x4T< T > & C) const inline
Multiplication operator with another matrix
References CD_Matrix::Matrix4x4T< T >::m.
template<typename T> void CD_Matrix::Matrix4x4T< T >::CeqthismulB (const Vector4T< T > & B, Vector4T< T > & C) const inline
Multiplication operator with another matrix
References CD_Matrix::Vector4T< T >::m_w, CD_Matrix::Vector4T< T >::m_x, CD_Matrix::Vector4T< T >::m_y, and CD_Matrix::Vector4T< T >::m_z.
template<typename T> T CD_Matrix::Matrix4x4T< T >::determinant () const inline
Determinant
Referenced by CD_Matrix::Matrix4x4T< T >::Inversion().
template<typename T> void CD_Matrix::Matrix4x4T< T >::Inversion (Matrix4x4T< T > & A) inline
Inversion
References CD_Matrix::Matrix4x4T< T >::determinant(), and CD_Matrix::Matrix4x4T< T >::m.
template<typename T> Matrix4x4T<T> CD_Matrix::Matrix4x4T< T >::Inversion () inline
Inversion
References CD_Matrix::Matrix4x4T< T >::determinant().
template<typename T> T& CD_Matrix::Matrix4x4T< T >::operator() (unsigned int i, unsigned int j) inline
Access by giving the (i,j) element.
template<typename T> T CD_Matrix::Matrix4x4T< T >::operator() (unsigned int i, unsigned int j) const inline
Access by giving the (i,j) element.
template<typename T> Matrix4x4T<T> CD_Matrix::Matrix4x4T< T >::operator* (const Matrix4x4T< T > & B) const inline
Multiplication operator with another matrix
References CD_Matrix::Matrix4x4T< T >::m.
template<typename T> template<bool b> Vector3T<T,b> CD_Matrix::Matrix4x4T< T >::operator* (const Vector3T< T, b > & B) const inline
Multiplication operator with another vector
References CD_Matrix::Vector3T< T, normOptimization >::m_x, CD_Matrix::Vector3T< T, normOptimization >::m_y, and CD_Matrix::Vector3T< T, normOptimization >::m_z.
template<typename T> Matrix4x4T<T> CD_Matrix::Matrix4x4T< T >::operator* (const double & r) inline
Multiplication operator with a constant
References CD_Matrix::Matrix4x4T< T >::m.
template<typename T> void CD_Matrix::Matrix4x4T< T >::operator*= (const Matrix4x4T< T > & B) inline
Local matrix multiplication.
References CD_Matrix::Matrix4x4T< T >::m.
template<typename T> Matrix4x4T<T> CD_Matrix::Matrix4x4T< T >::operator+ (const Matrix4x4T< T > & B) inline
Addition operator
References CD_Matrix::Matrix4x4T< T >::m.
template<typename T> void CD_Matrix::Matrix4x4T< T >::operator+= (const Matrix3x3T< T > & B) inline
Self matrix addition
References CD_Matrix::Matrix3x3T< T >::m.
template<typename T> struct Matrix4x4T< T > CD_Matrix::Matrix4x4T< T >::operator- (const struct Matrix4x4T< T > & B) inline
Substraction operator
References CD_Matrix::Matrix4x4T< T >::m.
template<typename T> void CD_Matrix::Matrix4x4T< T >::operator-= (const Matrix4x4T< T > & B) inline
Local matrix substraction
References CD_Matrix::Matrix4x4T< T >::m.
template<typename T> T& CD_Matrix::Matrix4x4T< T >::operator[] (unsigned int i) inline
ith element considering the matrix as an array.
template<typename T> const T& CD_Matrix::Matrix4x4T< T >::operator[] (unsigned int i) const inline
ith element considering the matrix as an array.
template<typename T> void CD_Matrix::Matrix4x4T< T >::setIdentity (void) inline
Set to identity
References CD_Matrix::Matrix4x4T< T >::setZero().
template<typename T> void CD_Matrix::Matrix4x4T< T >::setZero (void) inline
Set to zero matrix
Referenced by CD_Matrix::Matrix4x4T< T >::setIdentity().
template<typename T> T CD_Matrix::Matrix4x4T< T >::trace () const inline
template<typename T> Matrix4x4T<T> CD_Matrix::Matrix4x4T< T >::Transpose () inline
Transposition
Friends And Related Function Documentation
template<typename T> std::ostream& operator<< (std::ostream & os, Matrix4x4T< T > const & A) friend
Member Data Documentation
template<typename T> T CD_Matrix::Matrix4x4T< T >::m[16]
The data array.
Referenced by CD_Matrix::Matrix4x4T< T >::CeqthismulB(), CD_Matrix::Matrix4x4T< T >::Inversion(), CD_Matrix::Matrix4x4T< T >::Matrix4x4T(), CD_Matrix::Matrix4x4T< T >::operator*(), CD_Matrix::Matrix4x4T< T >::operator*=(), CD_Matrix::Matrix4x4T< T >::operator+(), CD_Matrix::Matrix4x4T< T >::operator-(), and CD_Matrix::Matrix4x4T< T >::operator-=().