sch-core: sch::S_Polyhedron Class Reference
sch::S_Polyhedron Class Reference
#include <sch/S_Polyhedron/S_Polyhedron.h>
Public Member Functions
SCH_API S_Polyhedron (void)
SCH_API S_Polyhedron (const S_Polyhedron &)
virtual SCH_API ~S_Polyhedron (void)
SCH_API const S_Polyhedron & operator= (const S_Polyhedron &)
virtual SCH_API void constructFromFile (const std::string &filename)
loads the polyhedron from a file. the file must be in the format of Qhull qconvex output, called with these options : \ "qconvex TI <input_filename> TO <output_filename> Qt o f"
virtual SCH_API void loadFromBinary (const std::string &filename)
Load the object from a binary archive.
virtual SCH_API void saveToBinary (const std::string &filename)
Save the object to a binary archive.
SCH_API void updateFastArrays ()
updates the fast access arrays, must be called after each polyhedron modification
SCH_API Point3 naiveSupport (const Vector3 &v) const
SCH_API void updateVertexNeighbors ()
updates the Neighborhood of the vertexes, must be called on polyhedron vertexes have no neighbors, or after calling clearNeighbors.
SCH_API void clearNeighbors ()
clears the neighbors tables;
SCH_API void clear ()
clears all the polyhedron;
SCH_API void deleteVertexesWithoutNeighbors ()
deletes aal the vertexes that dont have neighbors;
SCH_API int getTrianglesNumber () const
SCH_API Polyhedron_algorithms * getPolyhedronAlgorithm ()
template<class Archive >
void save (Archive &ar, const unsigned int) const
template<class Archive >
void load (Archive &ar, const unsigned int)
Public Member Functions inherited from sch::S_ObjectNonNormalized
SCH_API S_ObjectNonNormalized (void)
SCH_API ~S_ObjectNonNormalized (void)
virtual SCH_API Point3 support (const Vector3 &v) const
put the vector in objects coordinates, then calls l_support, without normalizing it
virtual SCH_API Point3 support (const Vector3 &v, int &LastFeature) const
put the vector in objects coordinates, then calls l_support, without normalizing it
template<class Archive >
void serialize (Archive &ar, const unsigned int)
Public Member Functions inherited from sch::S_Object
SCH_API S_Object (void)
virtual SCH_API ~S_Object (void)
SCH_API void setOrientation (const Matrix3x3 &Rotation)
SCH_API void setOrientation (const Scalar &r00, const Scalar &r01, const Scalar &r02, const Scalar &r10, const Scalar &r11, const Scalar &r12, const Scalar &r20, const Scalar &r21, const Scalar &r22)
SCH_API void setOrientation (const Quaternion quaternion)
SCH_API void setOrientation (const Scalar &q0, const Scalar &q1, const Scalar &q2, const Scalar &q3)
SCH_API void setOrientation (const Scalar &yaw, const Scalar &pitch, const Scalar &roll)
SCH_API void setOrientation (const Scalar *const p)
SCH_API void setOrientation (const Scalar &angle, const Vector3 &axe)
SCH_API void setPosition (const Vector3 &v)
Sets the position.
SCH_API void setPosition (const Scalar &x, const Scalar &y, const Scalar &z)
SCH_API void setPosition (const Scalar *const v)
SCH_API void setTransformation (const Matrix4x4 &transformation)
Sets the transformation matrix.
SCH_API void addRotation (const Matrix3x3 &Rotation)
composes the current orientation with a Rotation
SCH_API void addRotation (const Scalar &r00, const Scalar &r01, const Scalar &r02, const Scalar &r10, const Scalar &r11, const Scalar &r12, const Scalar &r20, const Scalar &r21, const Scalar &r22)
SCH_API void addRotation (const Quaternion quaternion)
SCH_API void addRotation (const Scalar &q0, const Scalar &q1, const Scalar &q2, const Scalar &q3)
SCH_API void addRotation (const Scalar &angle, const Vector3 &axe)
SCH_API void addRotation (const Scalar &yaw, const Scalar &pitch, const Scalar &roll)
SCH_API void addRotation (const Scalar *const p)
SCH_API void addScale (const Scalar &x, const Scalar &y, const Scalar &z)
composes the current transfornation with a scale
SCH_API void addTransformation (const Matrix4x4 &transformation)
composes the current transfornation with transformation matrix one
SCH_API void resetTransformation ()
loads Identity
SCH_API const Vector3 & getPosition () const
returns the position
SCH_API const Matrix3x3 & getOrientation () const
returns the orientation as a rotation matrix
SCH_API void getTransformationMatrix (Scalar *S) const
puts the transfomation matrix in a sclar array
int getSlices () const
int getStacks () const
const S_ObjectTimeStamp & checkStamp () const
returns the current time stamp
template<class Archive >
void serialize (Archive &ar, const unsigned int)
SCH_API void addTranslation (const Vector3 &v)
SCH_API void addTranslation (const Scalar *const v)
SCH_API void addTranslation (const Scalar &x, const Scalar &y, const Scalar &z)
Protected Member Functions
virtual SCH_API Point3 l_Support (const Vector3 &v, int &lastFeature) const
gives the support point for a given vector in local cordinates and a given last feature. MUST BE OVERLOADED.
virtual SCH_API S_ObjectType getType () const
must be overloaded to return the type
Protected Attributes
Polyhedron_algorithms poly
Protected Attributes inherited from sch::S_Object
S_ObjectTimeStamp stamp_
int stacks_
int slices_
Matrix3x3 mRot_
Vector3 trans_
Additional Inherited Members
Public Types inherited from sch::S_Object
enum S_ObjectType {
TS_Object,
TPolyhedron,
TSTP_BV,
TSphere,
TBox,
TSuperellipsoid,
TSTP_BV_WithPolyhedron,
T_Point,
T_Capsule
}
type of a solid object. Don't use it to cast !
Detailed Description
Examples:
example2.cpp.
Constructor & Destructor Documentation
SCH_API sch::S_Polyhedron::S_Polyhedron (void)
SCH_API sch::S_Polyhedron::S_Polyhedron (const S_Polyhedron &)
virtual SCH_API sch::S_Polyhedron::~S_Polyhedron (void) virtual
Member Function Documentation
SCH_API void sch::S_Polyhedron::clear ()
clears all the polyhedron;
SCH_API void sch::S_Polyhedron::clearNeighbors ()
clears the neighbors tables;
virtual SCH_API void sch::S_Polyhedron::constructFromFile (const std::string & filename) virtual
loads the polyhedron from a file. the file must be in the format of Qhull qconvex output, called with these options : \ "qconvex TI <input_filename> TO <output_filename> Qt o f"
Reimplemented from sch::S_Object.
Examples:
example2.cpp.
SCH_API void sch::S_Polyhedron::deleteVertexesWithoutNeighbors ()
deletes aal the vertexes that dont have neighbors;
SCH_API Polyhedron_algorithms* sch::S_Polyhedron::getPolyhedronAlgorithm () inline
References poly.
SCH_API int sch::S_Polyhedron::getTrianglesNumber () const
virtual SCH_API S_ObjectType sch::S_Polyhedron::getType () const protected virtual
must be overloaded to return the type
Reimplemented from sch::S_Object.
Referenced by load().
virtual SCH_API Point3 sch::S_Polyhedron::l_Support (const Vector3 & v, int & lastFeature) const protected virtual
gives the support point for a given vector in local cordinates and a given last feature. MUST BE OVERLOADED.
Parameters
v direction vector (normalized)
lastFeature tells in which feature we were in last query, amd returns the new one. very important in spatio-temporal coherence
Returns
returns the support point.
Implements sch::S_Object.
Referenced by load().
template<class Archive > void sch::S_Polyhedron::load (Archive & ar, const unsigned int) inline
References getType(), l_Support(), poly, SCH_API, updateFastArrays(), and updateVertexNeighbors().
virtual SCH_API void sch::S_Polyhedron::loadFromBinary (const std::string & filename) virtual
Load the object from a binary archive.
Parameters
filename path to the binary archive
SCH_API Point3 sch::S_Polyhedron::naiveSupport (const Vector3 & v) const
SCH_API const S_Polyhedron& sch::S_Polyhedron::operator= (const S_Polyhedron &)
template<class Archive > void sch::S_Polyhedron::save (Archive & ar, const unsigned int) const inline
References poly.
virtual SCH_API void sch::S_Polyhedron::saveToBinary (const std::string & filename) virtual
Save the object to a binary archive.
Parameters
filename path to the binary archive
SCH_API void sch::S_Polyhedron::updateFastArrays ()
updates the fast access arrays, must be called after each polyhedron modification
Referenced by load().
SCH_API void sch::S_Polyhedron::updateVertexNeighbors ()
updates the Neighborhood of the vertexes, must be called on polyhedron vertexes have no neighbors, or after calling clearNeighbors.
Referenced by load().
Member Data Documentation
Polyhedron_algorithms sch::S_Polyhedron::poly protected
Referenced by getPolyhedronAlgorithm(), load(), and save().