sch-core: sch::CD_Simplex Class Reference
sch::CD_Simplex Class Reference
#include <sch/CD/CD_Simplex.h>
Public Member Functions
SCH_API CD_Simplex (const Point3 &p)
SCH_API CD_Simplex (const Point3 &p1, const Point3 &p2)
SCH_API CD_Simplex (const Point3 &p1, const Point3 &p2, const Point3 &p3)
SCH_API CD_Simplex (const Point3 &p1, const Point3 &p2, const Point3 &p3, const Point3 &p4)
virtual SCH_API ~CD_Simplex ()
SCH_API CD_SimplexType getType () const
SCH_API const Point3 & operator[] (unsigned char) const
SCH_API Point3 & operator[] (unsigned char)
SCH_API CD_Simplex & operator= (const CD_Simplex &s)
SCH_API CD_Simplex & operator= (const Point3 &p)
SCH_API bool operator== (const CD_Simplex &s)
SCH_API bool operator!= (const CD_Simplex &s)
SCH_API CD_Simplex & operator+= (const Point3 &)
Adds a point to a simplex to transform it in a higher dimemsion simplex (doesn't work with tetrahedron) must be called after this operator to keep the vectors up to date.
SCH_API CD_Simplex operator+ (const Point3 &) const
Adds a point to a simplex to transform it in a higher dimemsion simplex (doesn't work with tetrahedron) must be called after this operator to keep the vectors up to date.
virtual SCH_API void filter (const CD_SimplexKeptPoints &k)
Updates the simplex by supressing some vertexes and/or change their order according to a filter.
SCH_API Scalar squareDistanceAtOrigin (const Vector3 &v) const
Gives the distance squared at the origin for a simplex, and according the direction v.
SCH_API void updateVectors ()
Updates AB,AC,AD vectors. A is the last vertex inserted and B, C and D are previous vertexes.
SCH_API const Vector3 & AB () const
Returns AB vector.
SCH_API const Vector3 & AC () const
Returns AC vector.
SCH_API const Vector3 & AD () const
Returns AD vector.
Protected Attributes
CD_SimplexType type_
Point3 s1_
Point3 s2_
Point3 s3_
Point3 s4_
Vector3 ab_
Vector3 ac_
Vector3 ad_
Static Protected Attributes
static const Scalar zero_
static const Scalar zero2_
static const Scalar zero3_
static const Scalar zero4_
Constructor & Destructor Documentation
CD_Simplex() [1/4]
CD_Simplex::CD_Simplex (const Point3 & p) inline
Referenced by CD_SimplexExchange().
CD_Simplex() [2/4]
CD_Simplex::CD_Simplex (const Point3 & p1, const Point3 & p2) inline
CD_Simplex() [3/4]
CD_Simplex::CD_Simplex (const Point3 & p1, const Point3 & p2, const Point3 & p3) inline
CD_Simplex() [4/4]
CD_Simplex::CD_Simplex (const Point3 & p1, const Point3 & p2, const Point3 & p3, const Point3 & p4) inline
~CD_Simplex()
virtual SCH_API sch::CD_Simplex::~CD_Simplex () virtual
Member Function Documentation
AB()
const Vector3 & CD_Simplex::AB () const inline
Returns AB vector.
Referenced by CD_SimplexExchange().
AC()
const Vector3 & CD_Simplex::AC () const inline
Returns AC vector.
Referenced by CD_SimplexExchange().
AD()
const Vector3 & CD_Simplex::AD () const inline
Returns AD vector.
Referenced by CD_SimplexExchange().
filter()
void CD_Simplex::filter (const CD_SimplexKeptPoints & k) inline virtual
Updates the simplex by supressing some vertexes and/or change their order according to a filter.
Parameters
k is the filter used to know wich vertexes will be kept and in wich order must be called after this function to keep the vectors up to date.
Reimplemented in sch::CD_SimplexEnhanced.
Referenced by CD_SimplexExchange().
getType()
CD_SimplexType CD_Simplex::getType () const inline
Referenced by CD_SimplexExchange().
operator!=()
bool CD_Simplex::operator!= (const CD_Simplex & s) inline
Referenced by CD_SimplexExchange().
operator+()
CD_Simplex CD_Simplex::operator+ (const Point3 & p) const inline
Adds a point to a simplex to transform it in a higher dimemsion simplex (doesn't work with tetrahedron) must be called after this operator to keep the vectors up to date.
Referenced by CD_SimplexExchange().
operator+=()
CD_Simplex & CD_Simplex::operator+= (const Point3 & p) inline
Adds a point to a simplex to transform it in a higher dimemsion simplex (doesn't work with tetrahedron) must be called after this operator to keep the vectors up to date.
Referenced by CD_SimplexExchange().
operator=() [1/2]
CD_Simplex & CD_Simplex::operator= (const CD_Simplex & s) inline
Referenced by CD_SimplexExchange().
operator=() [2/2]
CD_Simplex & CD_Simplex::operator= (const Point3 & p) inline
operator==()
bool CD_Simplex::operator== (const CD_Simplex & s) inline
Referenced by CD_SimplexExchange().
operator[]() [1/2]
const Point3 & sch::CD_Simplex::operator[] (unsigned char i) const inline
Referenced by CD_SimplexExchange().
operator[]() [2/2]
Point3 & sch::CD_Simplex::operator[] (unsigned char i) inline
squareDistanceAtOrigin()
Scalar CD_Simplex::squareDistanceAtOrigin (const Vector3 & v) const inline
Gives the distance squared at the origin for a simplex, and according the direction v.
Referenced by CD_SimplexExchange().
updateVectors()
void CD_Simplex::updateVectors () inline
Updates AB,AC,AD vectors. A is the last vertex inserted and B, C and D are previous vertexes.
References sch::CD_SimplexKeptPoints::operator[](), and SCH_API.
Referenced by CD_SimplexExchange().
Member Data Documentation
ab_
Vector3 sch::CD_Simplex::ab_ protected
Referenced by CD_SimplexExchange().
ac_
Vector3 sch::CD_Simplex::ac_ protected
Referenced by CD_SimplexExchange().
ad_
Vector3 sch::CD_Simplex::ad_ protected
Referenced by CD_SimplexExchange().
s1_
Point3 sch::CD_Simplex::s1_ protected
Referenced by CD_SimplexExchange().
s2_
Point3 sch::CD_Simplex::s2_ protected
Referenced by CD_SimplexExchange().
s3_
Point3 sch::CD_Simplex::s3_ protected
Referenced by CD_SimplexExchange().
s4_
Point3 sch::CD_Simplex::s4_ protected
Referenced by CD_SimplexExchange().
type_
CD_SimplexType sch::CD_Simplex::type_ protected
Referenced by CD_SimplexExchange().
zero2_
const Scalar sch::CD_Simplex::zero2_ static protected
zero3_
const Scalar sch::CD_Simplex::zero3_ static protected
zero4_
const Scalar sch::CD_Simplex::zero4_ static protected
zero_
const Scalar sch::CD_Simplex::zero_ static protected