sch-core: CD_Matrix::Norm< T, normOptimization > Struct Template Reference
CD_Matrix::Norm< T, normOptimization > Struct Template Reference
#include <sch/Matrix/SmallVector3T.h>
Public Member Functions
Norm ()
void setNorm (const T &n)
void outdateNorm ()
bool normOutdated () const
T getNorm () const
Protected Attributes
T norm_
bool normOutdated_
Constructor & Destructor Documentation
Norm()
template<typename T, bool normOptimization> CD_Matrix::Norm< T, normOptimization >::Norm () inline
Member Function Documentation
getNorm()
template<typename T, bool normOptimization> T CD_Matrix::Norm< T, normOptimization >::getNorm () const inline
Referenced by CD_Matrix::Vector3T< Scalar, false >::optimizedNorm().
normOutdated()
template<typename T, bool normOptimization> bool CD_Matrix::Norm< T, normOptimization >::normOutdated () const inline
outdateNorm()
template<typename T, bool normOptimization> void CD_Matrix::Norm< T, normOptimization >::outdateNorm () inline
Referenced by CD_Matrix::Vector3T< Scalar, false >::normalize(), CD_Matrix::Vector3T< Scalar, false >::operator()(), CD_Matrix::Vector3T< Scalar, false >::operator*=(), CD_Matrix::Vector3T< Scalar, false >::operator+=(), CD_Matrix::Vector3T< Scalar, false >::operator-=(), CD_Matrix::Vector3T< Scalar, false >::operator/=(), CD_Matrix::Vector3T< Scalar, false >::operator=(), CD_Matrix::Vector3T< Scalar, false >::operator[](), CD_Matrix::Vector3T< Scalar, false >::serialize(), and CD_Matrix::Vector3T< Scalar, false >::Set().
setNorm()
template<typename T, bool normOptimization> void CD_Matrix::Norm< T, normOptimization >::setNorm (const T & n) inline
Referenced by CD_Matrix::Vector3T< Scalar, false >::optimizedNorm().
Member Data Documentation
norm_
template<typename T, bool normOptimization> T CD_Matrix::Norm< T, normOptimization >::norm_ protected
Referenced by CD_Matrix::Norm< Scalar, normOptimization >::getNorm().
normOutdated_
template<typename T, bool normOptimization> bool CD_Matrix::Norm< T, normOptimization >::normOutdated_ protected
Referenced by CD_Matrix::Norm< Scalar, normOptimization >::normOutdated().